# 예외 처리


## 에러 ERROR

- 능력 밖의 오류. 자바가 동작하는 환경에서 문제가 생긴 것.
- 메모리가 부족하거나 운영체제의 문제 등..
- 대비 불가

# 예외 EXCEPTION

- 작성한 코드가 의도와 다른 상황에 직면했을 때..
- 사용자의 예상치 못한 입력값, 읽으려고 했던 파일을 찾을 수 없는 문제 등..
- 예상하지 못한 예외상황
- 대비 가능


## try-catch문

- try - catch문을 사용하여 예외상황 발생시 catch문을 실행하고 나머지 코드 실행 가능.
- try문 안의 코드들은 예외를 만났을 때 catch문으로 이동한다. (try문 내 나머지 코드는 실행 X)
- catch문도 순차적으로 실행되므로 위에 있는 catch문이 우선순위.
- Exception class는 다른 모든 Exception 관련 클래스들의 부모이다. 그러므로 Exception e로 모든 예외를 모아 한번에 처리하는 것도 가능.
- catch문의 e 인스턴스 변수의 메소드를 활용할 수 있다. **getMessage()메소드**를 이용하면 예외 상황에 대한 정보를 얻을 수 있고, **printStackTrace()메소드**를 사용하면 자바 에러문(예외 코드 위치, 예외 종류, 예외 원인)을 출력할 수 있다.
- 다만, 이러한 정보를 통해 코드의 내용이나 구조 등을 나쁜 의도를 가진 사람들에게 노출할 수도 있기 때문에 보통 이러한 정보를 사용자가 직접 볼 수 있게 구성하지는 않고, 서버 측에서 로그 파일 등을 이용해 관리자만 볼 수 있게 처리한다.
- finally문은 무조건 실행


## checked exception vs unchecked exception

- **unchecked exception**은 try - catch문을 작성하지 않고 프로그램이 중간에 뻗더라도 일단 컴파일 후 실행된다. Runtime Exception 클래스와 그로부터 상속된 모든 Exception이다.
- checked exception은 try - catch문을 작성하지 않으면 아예 컴파일되지 않는다. Runtime Exception을 제외한 모든 에러와 예외들이 checked exception에 속하며, checked exception은 반드시 예외처리를 해주어야 컴파일 할 수 있다.


## try-with-resource문

- 외부 리소스들을 사용할 때에는 접근이 끝났을 때 close()를 해주어야 함
- AutoCloseable 인터페이스를 구현하고 있는 클래스에서 사용 가능
- try-with-resource 문은 **try** 문에 괄호를 추가하여 그 안에 사용할 자원을 정의한다. **객체를 여러 개 선언할 수도 있고, 세미콜론(;)으로 구별한다.** 전체 try 문(try, catch, finally 등)이 종료되면 생성된 인스턴스는 자동으로 종료되기 때문에 명시적으로 close를 이용하지 않는다.

```jsx
import java.io.FileWriter;
import java.io.IOException;

public class TryWithResource {

	public static void main(String[] args) {
		try (FileWriter f = new FileWriter("data.txt")) {
			f.write("Hello");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
```


## throw Exception

- 코드에서 직접 예외를 발생시킬 때 사용

```jsx
public class MyException {

	public static void main(String[] args) {
		throw new RuntimeException("무언가 문제가 있습니다.");

	}

}
```


## throws Exception

- 예외를 코드를 사용하는 쪽에서 처리하게 넘김
- 예외처리를 해당 코드에서 할 필요가 없음

```jsx
import java.io.FileWriter;
import java.io.IOException;

public class ThrowException {

	public static void main(String[] args) throws IOException {
		FileWriter f = new FileWriter("./data.txt");
		f.write("Hello");
		f.close();
	}

}
```
